env:
    browser: true
    es6: true
parser: '@typescript-eslint/parser'
extends:
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'prettier/@typescript-eslint'
    - 'plugin:prettier/recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
settings:
    react:
        version: detect
rules:
    prettier/prettier: error
    react/prop-types: off
